# Generated by Django 5.2.14 on 2026-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('nome_medico', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=50)),
                ('localizacao', models.CharField(max_length=100)),
            ],
        ),
    ]
